//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFi.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniFi.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup generation error.
        /// </summary>
        public static string Backup_Error_Generation {
            get {
                return ResourceManager.GetString("Backup_Error_Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename cannot be empty.
        /// </summary>
        public static string Backup_Info_NotEmpty_Filename {
            get {
                return ResourceManager.GetString("Backup_Info_NotEmpty_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup named &quot;{0}&quot; not found.
        /// </summary>
        public static string Backup_Info_NotFound_Filename {
            get {
                return ResourceManager.GetString("Backup_Info_NotFound_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create/edit firewall group.
        /// </summary>
        public static string FirewallGroup_Error {
            get {
                return ResourceManager.GetString("FirewallGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall group {0} already exist.
        /// </summary>
        public static string FirewallGroup_Error_AlreadyExist {
            get {
                return ResourceManager.GetString("FirewallGroup_Error_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members cannot be empty.
        /// </summary>
        public static string FirewallGroup_Error_NotEmpty_Members {
            get {
                return ResourceManager.GetString("FirewallGroup_Error_NotEmpty_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall group {0} not found.
        /// </summary>
        public static string FirewallGroup_Error_NotFound {
            get {
                return ResourceManager.GetString("FirewallGroup_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall group id {0} not found.
        /// </summary>
        public static string FirewallGroup_Error_NotFound_Id {
            get {
                return ResourceManager.GetString("FirewallGroup_Error_NotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Global_Error {
            get {
                return ResourceManager.GetString("Global_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Global_Successful {
            get {
                return ResourceManager.GetString("Global_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group id cannot be empty.
        /// </summary>
        public static string Groups_Error_GroupId_NotEmpty {
            get {
                return ResourceManager.GetString("Groups_Error_GroupId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name cannot be empty.
        /// </summary>
        public static string Groups_Error_GroupName_NotEmpty {
            get {
                return ResourceManager.GetString("Groups_Error_GroupName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac address cannot be empty.
        /// </summary>
        public static string Services_NotEmpty_MacAddress {
            get {
                return ResourceManager.GetString("Services_NotEmpty_MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create/edit user group.
        /// </summary>
        public static string UserGroup_Error {
            get {
                return ResourceManager.GetString("UserGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group {0} already exist.
        /// </summary>
        public static string UserGroup_Error_AlreadyExist {
            get {
                return ResourceManager.GetString("UserGroup_Error_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error create usergroup {0}.
        /// </summary>
        public static string UserGroup_Error_Create {
            get {
                return ResourceManager.GetString("UserGroup_Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete group {0}.
        /// </summary>
        public static string UserGroup_Error_DeleteGroup {
            get {
                return ResourceManager.GetString("UserGroup_Error_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group {0} not found.
        /// </summary>
        public static string UserGroup_Error_NotFound {
            get {
                return ResourceManager.GetString("UserGroup_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group id {0} not found.
        /// </summary>
        public static string UserGroup_Error_NotFound_Id {
            get {
                return ResourceManager.GetString("UserGroup_Error_NotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        public static string Validate_Error_FirmwareUrl {
            get {
                return ResourceManager.GetString("Validate_Error_FirmwareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &quot;{0}&quot; is not a MAC address.
        /// </summary>
        public static string Validate_Error_MacAddress {
            get {
                return ResourceManager.GetString("Validate_Error_MacAddress", resourceCulture);
            }
        }
    }
}
